# ------------------------------
# Stages will involve initial build, staging & testing area, followed by an azure deployment job.
stages:
  - deploy
  - post-deploy
deploy-azure:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: mcr.microsoft.com/azure-cli:latest
  only:
    - feature/kudu_service_auth #Change to your branch for testing. Change back to main/develop before merging
  script:
    - az login -u $DEVID -p $DEVPASSWORD
    - az webapp up --name $DEVAPPNAME --resource-group $DEVRESOURCEGROUP --runtime "NODE|16-lts"
    - az rest --method POST --uri 'https://archemapp.scm.azurewebsites.net/basicauth/DebugConsole' --headers 'Authorization=Basic JGFyY2hlbWFwcDoyYnQzdVR5MVJhd1c3ZkR5dFdpd2wwaXlqSEJoWGJETWtrYWl2bDdaZzV6c3NZUlp0eGpsdUZ0WWRqcWw='
 

# kudu-auth:
#   stage: post-deploy
#   image: mcr.microsoft.com/azure-powershell:latest
#   script:
#     - Invoke-WebRequest -Uri 'https://archemapp.scm.azurewebsites.net/basicauth/DebugConsole' -Method POST -Headers @{'Authorization' = 'Basic JGFyY2hlbWFwcDoyYnQzdVR5MVJhd1c3ZkR5dFdpd2wwaXlqSEJoWGJETWtrYWl2bDdaZzV6c3NZUlp0eGpsdUZ0WWRqcWw=''Cookie' = 'ARRAffinity=cbe9e9718f0d822410f26ed3f330ac773a82055728017e0ba3ca3b7f294aae71; ARRAffinitySameSite=cbe9e9718f0d822410f26ed3f330ac773a82055728017e0ba3ca3b7f294aae71'}
