# ------------------------------
# Stages will involve initial build, staging & testing area, followed by an azure deployment job.
stages:
  - deploy
  - post-deploy
deploy-azure:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: mcr.microsoft.com/azure-cli:latest
  only:
    - feature/kudu_service_auth #Change to your branch for testing. Change back to main/develop before merging
  script:
    - az login -u $DEVID -p $DEVPASSWORD
    - az webapp up --name $DEVAPPNAME --resource-group $DEVRESOURCEGROUP --runtime "NODE|16-lts"
kudu-scm-build:
  stage: post-deploy
  image: mcr.microsoft.com/azure-cli:latest
  script: |
    az rest --method POST --uri "https://archemapp.scm.azurewebsites.net/api/command" --headers "Content-Type=application/json" "Authorization=Basic JGFyY2hlbWFwcDoyYnQzdVR5MVJhd1c3ZkR5dFdpd2wwaXlqSEJoWGJETWtrYWl2bDdaZzV6c3NZUlp0eGpsdUZ0WWRqcWw=" --body "{\"command\": \"sh -c \\\"cd /home/site/wwwroot && npm install\\\"\"}"
