# ------------------------------
# Stages will involve initial build, staging & testing area, followed by an azure deployment job.
stages:
  - deploy
  - post-deploy
deploy-azure:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: mcr.microsoft.com/azure-cli:
  only:
    - main #Change to your branch for testing. Change back to main/develop before merging
  script:
    - az login --username $PRODID --password $PRODPASSWORD
    - az webapp up --name $PRODAPPNAME --resource-group $PRODRESOURCEGROUP --runtime "NODE|16-lts"
kudu-scm-build:
  stage: post-deploy
  image: mcr.microsoft.com/azure-cli:latest
  script: |
    az rest --method POST --uri "https://dalchemar.scm.azurewebsites.net/api/command" --headers "Content-Type=application/json" "Authorization=Basic JGRhbGNoZW1hcjpUWDN0NDQxaWFYVFBtOW5OcjI4WFdHRm5YaENncG1ZNVJkODNrUFFrSERpY3M2SnYxWGhXcm05ZU5nc0s=" --body "{\"command\": \"sh -c \\\"cd /home/site/wwwroot && npm install\\\"\"}"
