# deploy_azure:
#   stage: deploy
#   image: mcr.microsoft.com/azure-cli
#   only:
#     - deployment_mashuk #Change to your branch for testing. Change back to main/develop before merging
#   script:
#     - az login --tenant cc4642ad-3f59-43e8-91db-052daa4306ec
#     - az login --service-principal -u <app-id> -p $PASSWORD --tenant cc4642ad-3f59-43e8-91db-052daa4306ec

variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/'

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."